I got this error:
Error: Main method not found in class Main, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application

I think this is the end because I need to run an object but system asking me to add a "public static void main" that is not required here